/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_triangulation_free(a: number): void;
export function triangulation_new_default(a: number): number;
export function triangulation_new_from_vec(a: number, b: number): number;
export function triangulation_new(): number;
export function triangulation_insert(a: number, b: number, c: number): void;
export function triangulation_insert_one_pt(a: number, b: number, c: number, d: number): number;
export function triangulation_number_of_vertices(a: number): number;
export function triangulation_number_of_triangles(a: number): number;
export function triangulation_all_vertices(a: number, b: number): void;
export function triangulation_all_edges(a: number, b: number): void;
export function triangulation_all_triangles(a: number, b: number): void;
export function triangulation_closest_point(a: number, b: number, c: number): number;
export function triangulation_remove(a: number, b: number): number;
export function __wbg_matrix_free(a: number): void;
export function matrix_new(a: number, b: number): number;
export function matrix_new_from_vec(a: number, b: number, c: number): number;
export function matrix_set(a: number, b: number, c: number, d: number): number;
export function matrix_set_row(a: number, b: number, c: number, d: number): number;
export function matrix_get(a: number, b: number, c: number): number;
export function matrix_to_vec(a: number, b: number): void;
export function points(a: number, b: number): void;
export function start(): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_start(): void;
